namespace ITVComponents.DataAccess
{
    /// <summary>
    /// Interface describes a Controller for saving Items into the database
    /// </summary>
    public interface IController
    {
        /// <summary>
        /// Saves a Record in the database
        /// </summary>
        /// <param name="item">the item to save in the database</param>
        /// <returns>a value indicating whether the save process was successful</returns>
        bool Save(dynamic item);

        /// <summary>
        /// creates a new Record of the Controller type
        /// </summary>
        /// <returns>a new record that can contain data of the Controller's Recordtype</returns>
        dynamic New();

        /// <summary>
        /// Gets the index of an item retrieved from the database
        /// </summary>
        /// <param name="item">the recordItem generated by this controller</param>
        /// <returns>the value of the index for this item</returns>
        object GetIndex(dynamic item);

        /// <summary>
        /// Sets the index of an item that has just been added to the database
        /// </summary>
        /// <param name="item">the item that is now stored in the database</param>
        /// <param name="indexValue">the new indexvalue</param>
        void SetIndex(dynamic item, object indexValue);
    }
}
