<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>5.0.0-PRE026</Version>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RepositoryUrl>https://github.com/ITVenture/ITVComponents</RepositoryUrl>
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="md &quot;$(solutiondir)bin\$(targetFramework)&quot;&#xD;&#xA;md &quot;$(solutiondir)symbols\$(targetFramework)&quot;&#xD;&#xA;copy &quot;$(TargetPath)&quot; &quot;$(solutiondir)bin\$(targetFramework)\$(targetName).dll&quot;&#xD;&#xA;copy &quot;$(targetDir)$(targetName).deps.json&quot; &quot;$(solutiondir)bin\$(targetFramework)\$(targetName).deps.json&quot;&#xD;&#xA;copy &quot;$(targetDir)$(targetName).pdb&quot; &quot;$(solutiondir)symbols\$(targetFramework)\$(targetName).pdb&quot;" />
  </Target>
  <Target Name="MyPreCompileTarget" BeforeTargets="Build">
    <!--Exec Command="npx webpack" /-->
  </Target>
  <ItemGroup>
    <ProjectReference Include="..\ITVComponents.WebCoreToolkit.Net.SpaApi\ITVComponents.WebCoreToolkit.Net.SpaApi.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Common" version="4.14.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" version="4.14.0" />
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources\Handlers\LoginHandler.resx">
      <Generator>
      </Generator>
    </EmbeddedResource>
  </ItemGroup>
</Project>