<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>5.0.0-PRE155</Version>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RepositoryUrl>https://github.com/ITVenture/ITVComponents</RepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ITVComponents.Workflow\ITVComponents.Workflow.csproj" />
    <ProjectReference Include="..\ITVComponents.Workflow.Plugins\ITVComponents.Workflow.Plugins.csproj" />
    <ProjectReference Include="..\ITVComponents.Plugins\ITVComponents.Plugins.csproj" />
    <ProjectReference Include="..\ITVComponents.WebCoreToolkit\ITVComponents.WebCoreToolkit.csproj" />
  </ItemGroup>
</Project>