<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.3.3" />
    <PackageReference Include="MSTest.TestFramework" Version="4.3.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ITVComponents.Workflow.Plugins.WebCoreToolkit\ITVComponents.Workflow.Plugins.WebCoreToolkit.csproj" />
    <ProjectReference Include="..\ITVComponents.Workflow.Plugins\ITVComponents.Workflow.Plugins.csproj" />
    <ProjectReference Include="..\ITVComponents.Workflow\ITVComponents.Workflow.csproj" />
    <ProjectReference Include="..\ITVComponents.Plugins\ITVComponents.Plugins.csproj" />
    <ProjectReference Include="..\ITVComponents.WebCoreToolkit\ITVComponents.WebCoreToolkit.csproj" />
    <ProjectReference Include="..\ITVComponents.Workflow.WebWorker\ITVComponents.Workflow.WebWorker.csproj" />
  </ItemGroup>
</Project>