<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>5.0.0-PRE042</Version>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RepositoryUrl>https://github.com/ITVenture/ITVComponents</RepositoryUrl>
    <RazorCompileOnBuild>true</RazorCompileOnBuild>
    <RazorCompileOnPublish>true</RazorCompileOnPublish>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ITVComponents.DataAccess\ITVComponents.DataAccess.csproj" />
    <ProjectReference Include="..\ITVComponents.Decisions.Entities\ITVComponents.Decisions.Entities.csproj" />
    <ProjectReference Include="..\ITVComponents.DuckTyping\ITVComponents.DuckTyping.csproj" />
    <ProjectReference Include="..\ITVComponents.EFRepo\ITVComponents.EFRepo.csproj" />
    <ProjectReference Include="..\ITVComponents.Formatting\ITVComponents.Formatting.csproj" />
    <ProjectReference Include="..\ITVComponents.ParallelProcessing\ITVComponents.ParallelProcessing.csproj" />
    <ProjectReference Include="..\ITVComponents.Plugins\ITVComponents.Plugins.csproj" />
    <ProjectReference Include="..\ITVComponents.SettingsExtensions\ITVComponents.SettingsExtensions.csproj" />
    <ProjectReference Include="..\ITVComponents.WebCoreToolkit.EntityFramework\ITVComponents.WebCoreToolkit.EntityFramework.csproj" />
    <ProjectReference Include="..\ITVComponents.WebCoreToolkit\ITVComponents.WebCoreToolkit.csproj" />
    <ProjectReference Include="..\ITVComponents\ITVComponents.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Shared\Resources\TimeZoneTranslations.resx">
      <Generator>
      </Generator>
    </EmbeddedResource>
  </ItemGroup>
</Project>