// <auto-generated />
using System;
using ITVComponents.Workflow.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ITVComponents.Workflow.EntityFramework.PostgreSql.Migrations
{
    [DbContext(typeof(WorkflowContext))]
    [Migration("20260804061400_JoinArrivalAndSubProcess")]
    partial class JoinArrivalAndSubProcess
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ITVComponents.Workflow.EntityFramework.HistoryEntryRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<string>("Event")
                        .HasColumnType("text");

                    b.Property<string>("InstanceId")
                        .HasColumnType("text");

                    b.Property<string>("NodeId")
                        .HasColumnType("text");

                    b.Property<string>("RootInstanceId")
                        .HasColumnType("text");

                    b.Property<int>("Seq")
                        .HasColumnType("integer");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId");

                    b.HasIndex("RootInstanceId");

                    b.HasIndex("Severity");

                    b.HasIndex("InstanceId", "Seq");

                    b.ToTable("HistoryEntries");
                });

            modelBuilder.Entity("ITVComponents.Workflow.EntityFramework.TokenRow", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasColumnType("text");

                    b.Property<string>("TokenId")
                        .HasColumnType("text");

                    b.Property<string>("ArrivedViaFlowId")
                        .HasColumnType("text");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("text");

                    b.Property<int?>("BoundaryIteration")
                        .HasColumnType("integer");

                    b.Property<string>("BoundaryOwnerTokenId")
                        .HasColumnType("text");

                    b.Property<string>("ClaimedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ClaimedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DueUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NodeId")
                        .HasColumnType("text");

                    b.Property<string>("RaceTokenId")
                        .HasColumnType("text");

                    b.Property<string>("SplitTokenId")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SubProcessOwnerTokenId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TaskCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TaskDueUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TaskKey")
                        .HasColumnType("text");

                    b.Property<string>("TaskPermission")
                        .HasColumnType("text");

                    b.Property<string>("TaskTitle")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<string>("TimerLeaseOwner")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TimerLeaseUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VariablesJson")
                        .HasColumnType("text");

                    b.Property<string>("WaitingCorrelation")
                        .HasColumnType("text");

                    b.Property<string>("WaitingForChildInstanceId")
                        .HasColumnType("text");

                    b.Property<int?>("WaitingKind")
                        .HasColumnType("integer");

                    b.Property<string>("WaitingSignal")
                        .HasColumnType("text");

                    b.Property<string>("WaitingTarget")
                        .HasColumnType("text");

                    b.HasKey("InstanceId", "TokenId");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("DueUtc");

                    b.HasIndex("InstanceId");

                    b.HasIndex("Status");

                    b.HasIndex("WaitingCorrelation");

                    b.HasIndex("WaitingSignal");

                    b.HasIndex("WaitingTarget");

                    b.HasIndex("WaitingSignal", "WaitingKind");

                    b.HasIndex("TenantId", "TaskKey", "Status");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("ITVComponents.Workflow.EntityFramework.WorkflowBranchLockRow", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasColumnType("text");

                    b.Property<string>("TokenId")
                        .HasColumnType("text");

                    b.Property<DateTime>("AcquiredUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Owner")
                        .HasColumnType("text");

                    b.HasKey("InstanceId", "TokenId");

                    b.HasIndex("Owner");

                    b.ToTable("BranchLocks");
                });

            modelBuilder.Entity("ITVComponents.Workflow.EntityFramework.WorkflowDefinitionRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<string>("DefinitionJson")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.HasKey("Id", "Version");

                    b.HasIndex("TenantId");

                    b.ToTable("WorkflowDefinitions");
                });

            modelBuilder.Entity("ITVComponents.Workflow.EntityFramework.WorkflowInstanceRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("CallDepth")
                        .HasColumnType("integer");

                    b.Property<string>("CorrelationKey")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefinitionId")
                        .HasColumnType("text");

                    b.Property<int>("DefinitionVersion")
                        .HasColumnType("integer");

                    b.Property<string>("FaultMessage")
                        .HasColumnType("text");

                    b.Property<string>("ParentInstanceId")
                        .HasColumnType("text");

                    b.Property<string>("ParentTokenId")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<string>("RootInstanceId")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VariablesJson")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationKey");

                    b.HasIndex("ParentInstanceId");

                    b.HasIndex("RootInstanceId");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.HasIndex("Status", "Priority");

                    b.ToTable("WorkflowInstances");
                });
#pragma warning restore 612, 618
        }
    }
}
