using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using ITVComponents.DataAccess;

namespace ITVComponents.DataExchange.Import
{
    /// <summary>
    /// Describes an Event-Listener for specific Parser - Events
    /// </summary>
    public interface IParserEventListener
    {
        /// <summary>
        /// Adds a Dumper to the list of available Dumpers for this listener
        /// </summary>
        /// <param name="dumper">a dumper object that is used to write the generated log-messages to specific target</param>
        void AddDumper(IParserEventDumper dumper);

        /// <summary>
        /// Removes the given Dumper from the list of available Dumpers
        /// </summary>
        /// <param name="dumper">the dumper object to remove from the list of available dumpers</param>
        bool RemoveDumper(IParserEventDumper dumper);

        /// <summary>
        /// Removes all Dumpers from this Parser-Listener
        /// </summary>
        void ClearDumpers();

        /// <summary>
        /// Reports an event for a specific input-dataset
        /// </summary>
        /// <param name="data">the data that was generated by a specific source</param>
        /// <param name="message">the message that was generated by the parser or the source</param>
        /// <param name="severity">the severity of the event</param>
        /// <param name="result">the result that was generated by the parser</param>
        void ReportEvent(object data, string message, ParserEventSeverity severity, DynamicResult result = null);

        /// <summary>
        /// Dumps all Reports to the attached Dumper-objects
        /// </summary>
        void DumpAllReports();
    }

    /// <summary>
    /// Parser Event Categories 
    /// </summary>
    [Flags]
    public enum ParserEventSeverity
    {
        /// <summary>
        /// The event is a simple Report
        /// </summary>
        Report = 1,

        /// <summary>
        /// The event is a Warning
        /// </summary>
        Warning = 2,

        /// <summary>
        /// The event is an Error
        /// </summary>
        Error = 4
    }
}
