<Project Sdk="Microsoft.NET.Sdk.Razor" ToolsVersion="15.0">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>5.0.0-PRE165</Version>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RepositoryUrl>https://github.com/ITVenture/ITVComponents</RepositoryUrl>
    <RazorCompileOnBuild>true</RazorCompileOnBuild>
    <RazorCompileOnPublish>true</RazorCompileOnPublish>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="md &quot;$(solutiondir)bin\$(targetFramework)&quot;&#xD;&#xA;md &quot;$(solutiondir)symbols\$(targetFramework)&quot;&#xD;&#xA;copy &quot;$(TargetPath)&quot; &quot;$(solutiondir)bin\$(targetFramework)\$(targetName).dll&quot;&#xD;&#xA;copy &quot;$(targetDir)$(targetName).deps.json&quot; &quot;$(solutiondir)bin\$(targetFramework)\$(targetName).deps.json&quot;&#xD;&#xA;copy &quot;$(targetDir)$(targetName).pdb&quot; &quot;$(solutiondir)symbols\$(targetFramework)\$(targetName).pdb&quot;" />
  </Target>
  <ItemGroup>
    <ProjectReference Include="..\ITVComponents.WebCoreToolkit.Extras\ITVComponents.WebCoreToolkit.Extras.csproj" />
    <ProjectReference Include="..\ITVComponents.WebCoreToolkit.InterProcessExtensions\ITVComponents.WebCoreToolkit.InterProcessExtensions.csproj" />
    <ProjectReference Include="..\ITVComponents.WebCoreToolkit.Net.TelerikUi.AdminViews\ITVComponents.WebCoreToolkit.Net.TelerikUi.AdminViews.csproj" />
    <ProjectReference Include="..\ITVComponents.WebCoreToolkit.IdentityShared\ITVComponents.WebCoreToolkit.IdentityShared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.10" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" version="5.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" version="5.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="wwwroot\js\" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources\Areas\Identity\IdentityMessages.de.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <Target Name="MyPreCompileTarget" BeforeTargets="Build">
  </Target>
</Project>