// <auto-generated />
using System;
using ITVComponents.Workflow.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITVComponents.Workflow.EntityFramework.SqlServer.Migrations
{
    [DbContext(typeof(WorkflowContext))]
    [Migration("20260819072748_WorkflowStartTriggers")]
    partial class WorkflowStartTriggers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITVComponents.Workflow.EntityFramework.HistoryEntryRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Event")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstanceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NodeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RootInstanceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Seq")
                        .HasColumnType("int");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId");

                    b.HasIndex("RootInstanceId");

                    b.HasIndex("Severity");

                    b.HasIndex("InstanceId", "Seq");

                    b.ToTable("HistoryEntries");
                });

            modelBuilder.Entity("ITVComponents.Workflow.EntityFramework.TokenRow", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TokenId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArrivedViaFlowId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("BoundaryIteration")
                        .HasColumnType("int");

                    b.Property<string>("BoundaryOwnerTokenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ClaimedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompensationOwnerTokenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NodeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RaceTokenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SplitBranchCount")
                        .HasColumnType("int");

                    b.Property<string>("SplitTokenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubProcessOwnerTokenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TaskCreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TaskDueUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TaskPermission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TimerLeaseOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TimerLeaseUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("VariablesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WaitingCorrelation")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WaitingForChildInstanceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WaitingKind")
                        .HasColumnType("int");

                    b.Property<string>("WaitingSignal")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WaitingTarget")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("InstanceId", "TokenId");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("DueUtc");

                    b.HasIndex("InstanceId");

                    b.HasIndex("Status");

                    b.HasIndex("WaitingCorrelation");

                    b.HasIndex("WaitingSignal");

                    b.HasIndex("WaitingTarget");

                    b.HasIndex("WaitingSignal", "WaitingKind");

                    b.HasIndex("TenantId", "TaskKey", "Status");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("ITVComponents.Workflow.EntityFramework.WorkflowBranchLockRow", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TokenId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AcquiredUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("InstanceId", "TokenId");

                    b.HasIndex("Owner");

                    b.ToTable("BranchLocks");
                });

            modelBuilder.Entity("ITVComponents.Workflow.EntityFramework.WorkflowDefinitionRow", b =>
                {
                    b.Property<int>("DefinitionKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DefinitionKey"));

                    b.Property<string>("DefinitionJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("DefinitionKey");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Id", "Version")
                        .IsUnique();

                    b.ToTable("WorkflowDefinitions");
                });

            modelBuilder.Entity("ITVComponents.Workflow.EntityFramework.WorkflowInstanceRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CallDepth")
                        .HasColumnType("int");

                    b.Property<string>("CompensationsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefinitionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DefinitionKey")
                        .HasColumnType("int");

                    b.Property<int>("DefinitionVersion")
                        .HasColumnType("int");

                    b.Property<string>("FaultMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentInstanceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ParentTokenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<string>("RootInstanceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("VariablesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationKey");

                    b.HasIndex("DefinitionKey");

                    b.HasIndex("ParentInstanceId");

                    b.HasIndex("RootInstanceId");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.HasIndex("Status", "Priority");

                    b.ToTable("WorkflowInstances");
                });

            modelBuilder.Entity("ITVComponents.Workflow.EntityFramework.WorkflowOutboxRow", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<bool>("Broadcast")
                        .HasColumnType("bit");

                    b.Property<string>("ClaimedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ClaimedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorrelationKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReachedVariable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetInstanceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WaitingTokenId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstanceId", "Id");

                    b.HasIndex("ClaimedUntil");

                    b.HasIndex("CreatedUtc");

                    b.ToTable("Outbox");
                });

            modelBuilder.Entity("ITVComponents.Workflow.EntityFramework.WorkflowStartTriggerRow", b =>
                {
                    b.Property<int>("TriggerKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TriggerKey"));

                    b.Property<bool>("AdoptCorrelationKey")
                        .HasColumnType("bit");

                    b.Property<string>("DefinitionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DefinitionKey")
                        .HasColumnType("int");

                    b.Property<int>("DefinitionVersion")
                        .HasColumnType("int");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("LastInstanceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastRunUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeaseOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LeaseUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextDueUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NodeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pattern")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignalName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("SkipWhilePreviousRuns")
                        .HasColumnType("bit");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VariablesJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TriggerKey");

                    b.HasIndex("DefinitionKey");

                    b.HasIndex("Kind", "NextDueUtc");

                    b.HasIndex("Kind", "SignalName");

                    b.HasIndex("TenantId", "DefinitionId");

                    b.ToTable("WorkflowStartTriggers");
                });

            modelBuilder.Entity("ITVComponents.Workflow.EntityFramework.WorkflowInstanceRow", b =>
                {
                    b.HasOne("ITVComponents.Workflow.EntityFramework.WorkflowDefinitionRow", null)
                        .WithMany()
                        .HasForeignKey("DefinitionKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ITVComponents.Workflow.EntityFramework.WorkflowStartTriggerRow", b =>
                {
                    b.HasOne("ITVComponents.Workflow.EntityFramework.WorkflowDefinitionRow", null)
                        .WithMany()
                        .HasForeignKey("DefinitionKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
