// <auto-generated />
using System;
using ITVComponents.Workflow.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITVComponents.Workflow.EntityFramework.SqlServer.Migrations
{
    [DbContext(typeof(WorkflowContext))]
    [Migration("20260726144436_InitialWorkflow")]
    partial class InitialWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITVComponents.Workflow.EntityFramework.HistoryEntryRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Event")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstanceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NodeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RootInstanceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Seq")
                        .HasColumnType("int");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId");

                    b.HasIndex("RootInstanceId");

                    b.HasIndex("Severity");

                    b.HasIndex("InstanceId", "Seq");

                    b.ToTable("HistoryEntries");
                });

            modelBuilder.Entity("ITVComponents.Workflow.EntityFramework.TokenRow", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TokenId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DueUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NodeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("WaitingForChildInstanceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WaitingSignal")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WaitingTarget")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("InstanceId", "TokenId");

                    b.HasIndex("DueUtc");

                    b.HasIndex("InstanceId");

                    b.HasIndex("Status");

                    b.HasIndex("WaitingSignal");

                    b.HasIndex("WaitingTarget");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("ITVComponents.Workflow.EntityFramework.WorkflowBranchLockRow", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TokenId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AcquiredUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("InstanceId", "TokenId");

                    b.HasIndex("Owner");

                    b.ToTable("BranchLocks");
                });

            modelBuilder.Entity("ITVComponents.Workflow.EntityFramework.WorkflowDefinitionRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<string>("DefinitionJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id", "Version");

                    b.HasIndex("TenantId");

                    b.ToTable("WorkflowDefinitions");
                });

            modelBuilder.Entity("ITVComponents.Workflow.EntityFramework.WorkflowInstanceRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CallDepth")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefinitionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DefinitionVersion")
                        .HasColumnType("int");

                    b.Property<string>("FaultMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentInstanceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ParentTokenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RootInstanceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("VariablesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationKey");

                    b.HasIndex("ParentInstanceId");

                    b.HasIndex("RootInstanceId");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.ToTable("WorkflowInstances");
                });
#pragma warning restore 612, 618
        }
    }
}
