<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>5.0.0-PRE185</Version>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RepositoryUrl>https://github.com/ITVenture/ITVComponents</RepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ITVComponents\ITVComponents.csproj" />
    <ProjectReference Include="..\ITVComponents.Formatting\ITVComponents.Formatting.csproj" />
    <ProjectReference Include="..\ITVComponents.Logging\ITVComponents.Logging.csproj" />
    <ProjectReference Include="..\ITVComponents.Scripting.CScript\ITVComponents.Scripting.CScript.csproj" />
  </ItemGroup>
</Project>